# Basic Site Settings
locale                   : "en-US"
title                    : "Syed Muhammad Hussain"
title_separator          : "-"
name                     : &name "Syed Muhammad Hussain"
description              : &description "Machine Learning Engineer specializing in AI-driven solutions"
url                      : https://syed-m-hussain.github.io 
baseurl                  : "" 
repository               : "syedhussain/portfolio-website"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Syed Muhammad Hussain"
  pronouns         : "he/him"  
  bio              : "Associate Machine Learning Engineer at Beam AI. Passionate about AI, deep learning, and automation."
  location         : "Karachi, Pakistan"
  employer         : "Beam AI"
  uri              : "https://www.linkedin.com/in/syed-muhammad-hussain-00b2a7214/" # If you have a personal website or blog
  email            : "sh06892@st.habib.edu.pk"  # Replace with your professional email

  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile if applicable
  googlescholar    : "https://scholar.google.com/citations?user=TqMFlMYAAAAJ&hl=en"
  impactstory      : # URL
  orcid            : "https://orcid.org/my-orcid?orcid=0009-0000-4613-845X"  # Replace with your ORCID
  semantic         : # URL
  pubmed           : # If applicable
  researchgate     : # URL if you have one

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "SYED-M-HUSSAIN"
  kaggle           : "syed_hussain"  # If you have a Kaggle account  
  stackoverflow    : "1234567/syed-muhammad-hussain"  # Replace with your Stack Overflow profile

  # Social media
  bluesky          : # Replace this with your Bluesky username
  facebook         : # If applicable
  flickr           : # If applicable
  foursquare       : # If applicable
  goodreads        : # If applicable
  google_plus      : # Deprecated
  keybase          : # If applicable
  instagram        : # Replace with your Instagram username
  lastfm           : # If applicable
  linkedin         : "syed-muhammad-hussain-00b2a7214"  # Replace with your LinkedIn username
  mastodon         : # URL if you use it
  medium           : "https://medium.com/@syedhussain"  # Replace with your Medium profile URL
  pinterest        : # If applicable
  soundcloud       : # If applicable
  steam            : # If applicable
  telegram         :  # Replace with your Telegram URL
  tumblr           : # If applicable
  twitter          : # Replace with your Twitter/X username
  vine             : # Deprecated
  weibo            : # If applicable
  wikipedia        : # If you have a Wikipedia page
  xing             : # If applicable
  youtube          : # Replace with your YouTube username
  zhihu            : # If applicable

# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
talkmap_link             : false 
comments:
  provider               : "disqus"  # Enable Disqus if you want to add comments
  disqus:
    shortname            : "syedhussain-comments"  # Replace with your Disqus shortname
  discourse:
    server               : 
  facebook:
    appid                :
    num_posts            : 
    colorscheme          : 
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" 
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" 
atom_feed:
  hide                   : false    
  path                   : 

# SEO Related
google_site_verification : # Add your Google site verification code
bing_site_verification   : # Add your Bing site verification code
alexa_site_verification  : # Add your Alexa site verification code
yandex_site_verification : # Add your Yandex site verification code

# Social Sharing
twitter:
  username               : &twitter "syedhussain"
facebook:
  username               : 
  app_id                 : 
  publisher              : 
og_image                 :  # Open Graph/Twitter default site image

# For specifying social profiles
social:
  type                   : "Person"
  name                   : "Syed Muhammad Hussain"
  links: 
    - "https://twitter.com/syedhussain"
    - "https://linkedin.com/in/syedhussain"
    - "https://github.com/syedhussain"

# Analytics
analytics:
  provider               : "google" 
  google:
    tracking_id          : "UA-XXXXX-Y"  # Replace with your Google Analytics tracking ID

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Outputting
permalink: /:categories/:title/
# paginate: 5 
# paginate_path: /page:num/
timezone: Asia/Karachi  # Set to your timezone

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
